### ISSUE TITLE
Target archive contains duplicates

### ISSUE THREAD

**Issue by dimitrystd** [outcoldman/docker-backup#4]
I reviewed archives and noticed that files can be present in it 2-3 or more times.
**Steps**:
Create folder with 2 files
```
/ # mkdir /tmp/backup
/ # touch /tmp/backup/1.txt /tmp/backup/2.txt
```
I want to backup all files in `/tmp/backup` except `2.txt`
```
/ # find /tmp/backup -not -path /tmp/backup/2.txt > /tmp/files-list
/ # cat /tmp/files-list
/tmp/backup
/tmp/backup/1.txt
```
Output looks correct.
Now try `tar` command from [backup](https://github.com/outcoldman/docker-backup/blob/master/backup)
```
/ # tar -cvz -f /dev/null -T /tmp/files-list
tar: removing leading '/' from member names
tmp/backup/
tmp/backup/2.txt
tmp/backup/1.txt
tmp/backup/1.txt
```
Tar backups folder and all its files. `2.txt` is present only once because it was not in list. `1.txt` was added when folder was scanned and once again because it's present in list.

**Expected**:
Tar archives only what is present in list, no automatic folder scan

**Comment by outcoldman** [comment]
Seems like a bug in your find arguments. Tar archived exactly what you have asked for, folder `/tmp/backup` with all includes and `/tmp/backup/1.txt`. You probably want to specify that you want to backup only `/tmp/backup/1.txt`.
